import type {
  BrandMenusResponse,
  BrandRecord,
  DishRecord,
  SelectOption,
} from "../../(modules)/product/brand-menus/types";

export const brandRecords: BrandRecord[] = [
  { id: "brand-flyfood", name: "Flyfood" },
  { id: "brand-asia", name: "Asia Kitchen" },
  { id: "brand-healthy", name: "Healthy Bites" },
];

export const categoryOptions: SelectOption[] = [
  { value: "cat-main", label: "Món chính" },
  { value: "cat-side", label: "Món phụ" },
  { value: "cat-dessert", label: "Tráng miệng" },
  { value: "cat-drink", label: "Đồ uống" },
];

export const dishRecords: DishRecord[] = [
  {
    id: "dish-01",
    name: "Gỏi gà xé phay",
    image: "/next.svg",
    code: "MN-GGXP",
    categoryId: "cat-main",
    brandId: "brand-flyfood",
    price: 120000,
    status: "selling",
    description: "Món gỏi gà xé phay truyền thống, đậm đà hương vị Việt.",
    sellingUnit: "Phần",
    nutritionalInfo: "Khoảng 350 calo/phần",
    allergenInfo: "Không có",
    shelfLifeStorage: "Bảo quản lạnh 0-4°C, dùng trong 24h.",
  },
  {
    id: "dish-02",
    name: "Canh chua cá hồi",
    image: "/next.svg",
    code: "MN-CCC",
    categoryId: "cat-main",
    brandId: "brand-flyfood",
    price: 150000,
    status: "selling",
    description: "Canh chua cá hồi tươi ngon, vị chua thanh, đậm đà.",
    sellingUnit: "Tô",
    nutritionalInfo: "Khoảng 280 calo/tô",
    allergenInfo: "Cá",
    shelfLifeStorage: "Bảo quản lạnh 0-4°C, dùng trong 24h.",
  },
  {
    id: "dish-03",
    name: "Chè khúc bạch",
    image: "/next.svg",
    code: "TM-CKB",
    categoryId: "cat-dessert",
    brandId: "brand-flyfood",
    price: 45000,
    status: "paused",
    description: "Chè khúc bạch thanh mát, ngọt dịu, giải nhiệt.",
    sellingUnit: "Chén",
    nutritionalInfo: "Khoảng 200 calo/chén",
    allergenInfo: "Sữa, hạnh nhân",
    shelfLifeStorage: "Bảo quản lạnh 0-4°C, dùng trong 12h.",
  },
  {
    id: "dish-04",
    name: "Nước ép ổi",
    image: "/next.svg",
    code: "DU-NEO",
    categoryId: "cat-drink",
    brandId: "brand-flyfood",
    price: 30000,
    status: "selling",
    description: "Nước ép ổi tươi nguyên chất, giàu vitamin C.",
    sellingUnit: "Ly",
    nutritionalInfo: "Khoảng 120 calo/ly",
    allergenInfo: "Không có",
    shelfLifeStorage: "Bảo quản lạnh 0-4°C, dùng trong 6h.",
  },
  {
    id: "dish-05",
    name: "Cơm chiên Dương Châu",
    image: "/next.svg",
    code: "AK-CCDC",
    categoryId: "cat-main",
    brandId: "brand-asia",
    price: 85000,
    status: "selling",
    description: "Cơm chiên Dương Châu thơm ngon, hạt cơm săn chắc.",
    sellingUnit: "Phần",
    nutritionalInfo: "Khoảng 400 calo/phần",
    allergenInfo: "Trứng, tôm",
    shelfLifeStorage: "Dùng nóng, không bảo quản.",
  },
  {
    id: "dish-06",
    name: "Mì xào giòn",
    image: "/next.svg",
    code: "AK-MXG",
    categoryId: "cat-main",
    brandId: "brand-asia",
    price: 90000,
    status: "selling",
    description: "Mì xào giòn với hải sản và rau củ tươi.",
    sellingUnit: "Phần",
    nutritionalInfo: "Khoảng 450 calo/phần",
    allergenInfo: "Hải sản, trứng",
    shelfLifeStorage: "Dùng nóng, không bảo quản.",
  },
  {
    id: "dish-07",
    name: "Salad ức gà",
    image: "/next.svg",
    code: "HB-SUG",
    categoryId: "cat-main",
    brandId: "brand-healthy",
    price: 110000,
    status: "selling",
    description: "Salad ức gà tươi mát, giàu protein và chất xơ.",
    sellingUnit: "Phần",
    nutritionalInfo: "Khoảng 250 calo/phần",
    allergenInfo: "Không có",
    shelfLifeStorage: "Bảo quản lạnh 0-4°C, dùng trong 12h.",
  },
];

export const brandMenusResponse: BrandMenusResponse = {
  brands: brandRecords,
  categories: categoryOptions,
  dishes: dishRecords,
};
